name: pyrosm_docs

channels:
  - conda-forge

dependencies:
  - python=3.7
  - sphinx=3.2
  - sphinx-book-theme
  - sphinx-thebe
  - ipython
  - jupyter-sphinx
  - IPython
  - jupyter_client
  - ipykernel
  - pip
  - pip:
    - myst-nb